name: wildfire-dl
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black=19.10b0
  - cudatoolkit=10.2.89
  - flake8=3.8.3
  - h5netcdf=0.8.1
  - imbalanced-learn=0.7.0
  - ipython=7.13.0
  - jupyter=1.0.0
  - jupyterlab=2.1.5
  - matplotlib=3.2.2
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - plac=0.9.6
  - pre-commit=2.5.1
  - python=3.7.7
  - pytorch=1.6.0
  - regionmask=0.5.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - sphinx=3.1.1
  - tensorboard=2.2.2
  - torchvision=0.7.0
  - pip:
    - gsutil==4.52
    - netcdf4==1.5.3
    - pytorch-lightning==0.9.0
    - sphinx-autoapi==1.4.0
    - wandb==0.8.36
