name: wildfire-dl
channels:
  - pytorch
  - anaconda
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.9.0
  - affine=2.3.0
  - alabaster=0.7.12
  - appdirs=1.4.3
  - argh=0.26.2
  - astroid=2.4.2
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - beautifulsoup4=4.9.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.4
  - blinker=1.4
  - bokeh=2.0.2
  - boost-cpp=1.72.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - cfgrib=0.9.8.2
  - cfgv=3.1.0
  - cfitsio=3.470
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cloudpickle=1.4.1
  - commonmark=0.9.1
  - cryptography=2.9.2
  - cudatoolkit=10.2.89
  - curl=7.69.1
  - cycler=0.10.0
  - cymem=2.0.2
  - cython-blis=0.2.4
  - cytoolz=0.10.1
  - dask=2.17.2
  - dask-core=2.17.2
  - dataclasses=0.6
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distlib=0.3.0
  - distributed=2.17.0
  - docopt=0.6.2
  - docutils=0.16
  - eccodes=2.18.0
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.2.9
  - fancycompleter=0.8
  - fastai=1.0.61
  - fastprogress=0.2.2
  - ffmpeg=4.3
  - filelock=3.0.12
  - fiona=1.8.13
  - fire=0.3.1
  - fish=3.1.2
  - flake8=3.8.3
  - fontconfig=2.13.1
  - freetype=2.9.1
  - freexl=1.0.5
  - fribidi=1.0.9
  - fsspec=0.7.4
  - future=0.18.2
  - fzf=0.21.1
  - gdal=3.0.4
  - geopandas=0.8.1
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.63.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - google-auth-oauthlib=0.4.1
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5netcdf=0.8.0
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=64.2
  - identify=1.4.20
  - idna=2.9
  - imageio=2.8.0
  - imagesize=1.2.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=1.900.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kealib=1.4.13
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lame=3.100
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.69.1
  - libdap4=3.20.6
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgdal=3.0.4
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopencv=4.3.0
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.12.3
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - livereload=2.6.2
  - locket=0.2.0
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - msgpack-python=1.0.0
  - munch=2.5.0
  - murmurhash=1.0.2
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - nettle=3.4.1
  - networkx=2.4
  - ninja=1.9.0
  - nodeenv=1.4.0
  - notebook=6.0.3
  - nspr=4.26
  - nss=3.47
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=4.3.0
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - owslib=0.20.0
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - partd=1.1.0
  - pathspec=0.7.0
  - pcre=8.44
  - pcre2=10.35
  - pdbpp=0.10.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pipreqs=0.4.10
  - pixman=0.38.0
  - plac=0.9.6
  - poppler=0.87.0
  - poppler-data=0.4.9
  - port-for=0.4
  - postgresql=12.3
  - pre-commit=2.5.1
  - preshed=2.0.1
  - proj=7.0.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py-opencv=4.3.0
  - pyasn1=0.4.8
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.0.2
  - pyepsg=0.4.0
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pyjwt=1.7.1
  - pylama=7.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-graphviz=0.14
  - python_abi=3.7
  - pytorch=1.5.0
  - pytorch-lightning=0.8.5
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - qt=5.12.5
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - rasterio=1.1.5
  - readline=8.0
  - recommonmark=0.6.0
  - regex=2020.5.14
  - regionmask=0.5.0
  - requests=2.23.0
  - rioxarray=0.0.31
  - rope=0.17.0
  - rstcheck=3.3.1
  - rtree=0.9.4
  - scikit-image=0.16.2
  - scipy=1.4.1
  - send2trash=1.5.0
  - setproctitle=1.1.10
  - setuptools=46.4.0
  - shapely=1.7.0
  - sip=4.19.8
  - six=1.14.0
  - snakeviz=2.0.1
  - snowballstemmer=2.0.0
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - soupsieve=2.0.1
  - spacy=2.1.8
  - sphinx=3.1.1
  - sphinx-autoapi=1.4.0
  - sphinx-autobuild=0.7.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-dotnetdomain=0.4
  - sphinxcontrib-golangdomain=0.2.0.dev0
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - srsly=0.1.0
  - tbb=2020.1
  - tblib=1.6.0
  - tensorboard=2.2.2
  - tensorboard-plugin-wit=1.6.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.0.8
  - tiledb=1.7.7
  - tk=8.6.10
  - toml=0.10.0
  - toolz=0.10.0
  - torchvision=0.6.0
  - tornado=6.0.4
  - tqdm=4.46.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - tzcode=2020a
  - unidecode=1.1.1
  - urllib3=1.25.8
  - virtualenv=20.0.20
  - wasabi=0.2.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wmctrl=0.3
  - wrapt=1.11.2
  - x264=1!152.20180806
  - xarray=0.15.1
  - xerces-c=3.2.2
  - xonsh=0.9.18
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.1.7
  - yarg=0.1.9
  - zeromq=4.3.1
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - args==0.1.0
    - blessings==1.7
    - cachetools==4.1.0
    - caliban==0.2.6
    - cdsapi==0.2.7
    - cftime==1.1.3
    - cligj==0.5.0
    - clint==0.5.1
    - commentjson==0.8.3
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - drawille==0.1.0
    - drawilleplot==0.1.0
    - ecmwf-api-client==1.5.4
    - flask==1.1.2
    - gitdb==4.0.5
    - gitpython==3.1.3
    - google-api-core==1.21.0
    - google-api-python-client==1.10.0
    - google-auth==1.19.2
    - google-auth-httplib2==0.0.4
    - google-cloud-container==2.0.0
    - google-cloud-core==1.3.0
    - googleapis-common-protos==1.52.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpc-google-iam-v1==0.12.3
    - grpcio==1.29.0
    - hiddenlayer==0.2
    - httplib2==0.18.1
    - itsdangerous==1.1.0
    - kubernetes==11.0.0
    - lark-parser==0.7.8
    - libcst==0.3.7
    - mako==1.1.3
    - msal==1.3.0
    - netcdf4==1.5.3
    - nonechucks==0.4.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - pathtools==0.1.2
    - pathvalidate==2.3.0
    - pdoc3==0.8.1
    - promise==2.3
    - proto-plus==1.3.0
    - protobuf==3.12.2
    - psycopg2-binary==2.8.5
    - pyasn1-modules==0.2.8
    - pycryptodome==3.9.7
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sentry-sdk==0.14.4
    - shortuuid==1.0.1
    - smmap==3.0.4
    - sqlalchemy==1.3.18
    - subprocess32==3.5.4
    - typing-inspect==0.6.0
    - uritemplate==3.0.1
    - wandb==0.8.36
    - watchdog==0.10.2
    - websocket-client==0.57.0
    - xshape==0.1.1
    - yaspin==0.17.0

