name: wildfire-dl
channels:
  - conda-forge
  - defaults
  - pytorch
  - anaconda
  - fastai
dependencies:
  - fastai
  - pytorch
  - torchvision
  - jupyter
  - cudatoolkit=10.2
  - cfgrib
  - black
  - dask
  - h5netcdf
  - pdbpp
  - xonsh
  - jinja2
  - fire
  - snakeviz
  - fzf
  - graphviz
  - python-graphviz
  - pylama
  - flake8
  - pre-commit
  - pip
  - pipreqs
  - sphinx
  - recommonmark
  - sphinx-autobuild
  - rstcheck
  - rope
  - sphinx-autoapi
  - opencv
  - scikit-image
  - pip:
    - absl-py==0.9.0
    - args==0.1.0
    - cachetools==4.1.0
    - cdsapi==0.2.7
    - cftime==1.1.3
    - cligj==0.5.0
    - clint==0.5.1
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - drawille==0.1.0
    - drawilleplot==0.1.0
    - ecmwf-api-client==1.5.4
    - flask==1.1.2
    - gitdb==4.0.5
    - gitpython==3.1.3
    - google-auth==1.16.0
    - google-auth-oauthlib==0.4.1
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.29.0
    - hiddenlayer==0.2
    - itsdangerous==1.1.0
    - mako==1.1.3
    - markdown==3.2.2
    - msal==1.3.0
    - netcdf4==1.5.3
    - nonechucks==0.4.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - pathtools==0.1.2
    - pathvalidate==2.3.0
    - pdoc3==0.8.1
    - promise==2.3
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.9.7
    - pyjwt==1.7.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytorch-lightning==0.8.1
    - rasterio==1.1.4
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sentry-sdk==0.14.4
    - shortuuid==1.0.1
    - smmap==3.0.4
    - subprocess32==3.5.4
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.6.0.post3
    - wandb==0.8.36
    - watchdog==0.10.2
    - werkzeug==1.0.1
    - xshape==0.1.1
prefix: /home/esowc/anaconda3/envs/wildfire-dl

