name: wildfire-dl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - h5netcdf=0.8.1
  - imbalanced-learn=0.7.0
  - jupyter=1.0.0
  - jupyterlab=2.1.5
  - matplotlib=3.2.2
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - plac=0.9.6
  - python=3.7.7
  - pytorch=1.6.0
  - regionmask=0.5.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - torchvision=0.7.0
  - pip:
    - gsutil==4.52
    - netcdf4==1.5.3
    - pytorch_lightning==0.9.0rc12
    - wandb==0.8.36
